package com.payments.audit.model;

public enum EventType {
    PAYMENT_INITIATED,
    PAYMENT_VALIDATED,
    PAYMENT_COMPLETED,
    PAYMENT_FAILED,
    ACCOUNT_CREATED,
    ACCOUNT_UPDATED,
    ACCOUNT_DEACTIVATED,
    BALANCE_HOLD_CREATED,
    BALANCE_HOLD_RELEASED,
    BALANCE_HOLD_DEBITED,
    NOTIFICATION_SENT,
    SETTLEMENT_STARTED,
    SETTLEMENT_COMPLETED,
    SETTLEMENT_FAILED
}
